### ISSUE TITLE
Make the `pickerView` independent of `Input.text`

### ISSUE THREAD

**Issue by valberg** [FabHof/elm-ui-datepicker#4]
I was thinking about that it would be nice to be able to have the `pickerView` itself independent of a `Input.text` element. Thus I could bind some other element's onClick to show the picker.

I have only skimmed the code, but it looks like we could expose `pickerView` without too much changes in the internals?

**Comment by FabHof** [comment]
Thanks for your input and sorry for my late answer. I'm happy someone is interested in this.
I have thought about this a bit. Two points that led me to not do it for now:

- Accessibility: Elm-ui inputs should always be accessible. I have no idea about accessibility, but I don't think my `pickerView` is accessible. But the `Input.text` is. 
- Default mouse actions are suppressed in the `pickerView` to keep the `Input.text` focused. This is more of a hack than a good solution. I'm not sure how I should handle this when I expose the `pickerView` - what would be the expected behaviour?
